service:
- docker

env:
  global:
  # github-api-v3-gateway app requires github token
  - secure: "PLL6z6iFOkP1zcJt2R7Yq8ut1313FX70opXUrC7/O0HUEgQdU1q77McSjxxyY4AtzvT+XPgbGNAx5JXuVpHyQ4rnM1Q/3HBz7E2ZHr+71ehLap95x9XKkwShw/Can9IYu66FUGm7sOdN2b01JOpH4IKR50tGeUY9dWzdld10f/Se5KaRjCtzCKsMyMPm02dhUvxvzLn0VWNQDuZC2hAsLsBGOBKc9cGcI03b0u98We8lqyaJ6FT6j0Fjd4t3CycOVR+0XrVbEJ3tFaILmSZoer+N76vqnY42sTyHfbNUPyJboZshy8A19AAngebw4yJWKaHQ+B3eowLcpDRoR32SYnFHgDMtDLLsKMVZeGBvUazORgQpl5YKQeInOKbSku796ZiWz7ciGsCm52ve9dymlX+PUzkfA9J9ylK4XRl9/yLNFfqtjmWLRkP0+V3qRtwCnLU3yd5ZQ7D8t1dhSNJHddvC75oH6Cn/KFOk+4h6jjo+hXOj64ZcjJF8bvYLbdhlFNbNdmq8I9MT0qge95UcufJ9pJk42PL1ojAmxw2REACdW3MMPfcSWukQAuzOgPeZYAjQ9zUIFBqkrrbH2j4Eo+wEq+wwxsgcmBSAkgjdLR9Ni1x/RcqrO1kZ3fXbIr/1P8XXF9d1l0oMDgNjgt64MVT0wwNyxOEPBwGXUO3TkFw="
  - TERM=dumb

language: java
jdk: openjdk8

#jdk:
#- openjdk8
#- oraclejdk8

install: true
before_install:

- sudo apt update -y >/dev/null || true
- sudo apt install -y --no-install-recommends docker-ce curl jq libxml2-utils python-pip >/dev/null
- sudo pip install docker-compose httpie >/dev/null
- nvm install 9
- npm i -g yarn
- source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 8080 8081 80

script:
- export root=$(pwd)

# mapdb
- bash gradlew -b ${root}/mapdb/build.gradle >/dev/null
- bash ${root}/mapdb/build/libs/*.jar &
- wait_for 8080
- http :8080 message=hello,\ max!
- http :8080 message=how\ are\ u\?
- stop_any 8080

# axon-vote
- bash mvnw -f ${root}/axon-vote/pom.xml >/dev/null
- bash ${root}/axon-vote/target/*.jar &
- wait_for 8080
- http :8080/api/v1/registration id=my-vote name=my=vote
- http put http://localhost:8080/api/v1/registration/approve/my-vote
- http post http://localhost:8080/api/v1/vote/my-vote electorId=dag
- http post http://localhost:8080/api/v1/vote/my-vote electorId=max
- http :8080
- stop_any 8080

## some-spring-boot-2-frontend
#- bash gradlew -b ${root}/some-spring-boot-2-frontend/build.gradle >/dev/null 2>&1
#- bash ${root}/some-spring-boot-2-frontend/build/libs/*.jar &
#- wait_for 8080
#- http :8080
#- stop_any 8080

# github-api-v3-gateway
- cp -Rf ${root}/github-api-v3-gateway/webflux-gateway/src/main/resources/config/application-github-default.properties ${root}/github-api-v3-gateway/webflux-gateway/src/main/resources/config/application-github.properties
- http -a "$GITHUB_TOKEN" https://api.github.com
#
- bash gradlew -b ${root}/github-api-v3-gateway/build.gradle >/dev/null
- bash ${root}/github-api-v3-gateway/webflux-gateway/build/libs/*.jar &
- wait_for 8080
- http :8080/github/props/manual
- http :8080/github/props
- http :8080/github/search/users/dagg\?page=0\&size=2
- http :8080/github/search/users/dagge\?page=0\&size=2
- http :8080/github/search/users/daggr\?page=0\&size=2
- stop_any 8080
#
- bash mvnw -f ${root}/github-api-v3-gateway/pom.xml >/dev/null
- bash mvnw -f ${root}/github-api-v3-gateway/pom.xml -pl webflux-gateway clean package com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
- sleep 15
- bash mvnw -f ${root}/github-api-v3-gateway/pom.xml -pl webflux-gateway com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down
#
- bash ${root}/github-api-v3-gateway/webflux-gateway/target/*.jar &
- wait_for 8080
- http :8080/github/props/manual
- http :8080/github/props
- http :8080
- http :8080/github/search/users/dagg\?page=0\&size=2
- http :8080/github/search/users/dagge\?page=0\&size=2
- http :8080/github/search/users/daggrok\?page=0\&size=2
- stop_any 8080
#
- docker-compose -f ${root}/github-api-v3-gateway/webflux-gateway/docker-compose-gradle.yaml build --force-rm --no-cache --pull
- docker-compose -f ${root}/github-api-v3-gateway/webflux-gateway/docker-compose-gradle.yaml up &
- sleep 20
- docker-compose -f ${root}/github-api-v3-gateway/webflux-gateway/docker-compose-gradle.yaml down -v &

# reactor-processors
- bash gradlew -b ${root}/reactor-processors/build.gradle >/dev/null
- bash mvnw -f ${root}/reactor-processors/pom.xml >/dev/null
- bash ${root}/reactor-processors/flux-sink/build/libs/*.jar &
- wait_for 8080
- curl http://127.0.0.1:8080 &
- http :8080 --stream &
- http :8080/message message=hi!
- http :8080/message message=hey!
- stop_any 8080

# reactive axon
- bash gradlew -b ${root}/axon-lock/build.gradle >/dev/null
- bash mvnw -f ${root}/axon-lock/pom.xml >/dev/null
- java -jar ${root}/axon-lock/axon-app/build/libs/*.jar &
- java -jar ${root}/axon-lock/axon-app/target/*.jar --server.port=8000 &
- wait_for 8080 8000
- http :8080 name=Max
- http :8000 name=Axon
- stop_any 8080 8000

## kotlin-beans-dsl
#- bash gradlew -b ${root}/kotlin-beans-dsl/build.gradle >/dev/null
#- java -jar ${root}/kotlin-beans-dsl/kotlin-config-dsl/build/libs/*.jar
#- bash mvnw -f ${root}/kotlin-beans-dsl/pom.xml >/dev/null
#- java -jar ${root}/kotlin-beans-dsl/kotlin-config-dsl/target/*.jar

## xml-wtf
#- bash gradlew -b ${root}/xml-wtf/build.gradle >/dev/null
#- java -jar ${root}/xml-wtf/kotlin-xml/build/libs/*.jar &
#- bash mvnw -f ${root}/xml-wtf/pom.xml >/dev/null
#- java -jar ${root}/xml-wtf/kotlin-xml/target/*.jar --server.port=8000 &
#- wait_for 8080 8000
#- http :8080
#- http :8000
#- stop_any 8080 8000
## maven docker
#- docker-compose -f ${root}/xml-wtf/docker-compose-maven.yaml build --force-rm --no-cache --pull
#- docker-compose -f ${root}/xml-wtf/docker-compose-maven.yaml up --force-recreate --remove-orphans &
#- sleep 20
#- http :8080
#- docker-compose -f ${root}/xml-wtf/docker-compose-maven.yaml down -v
## gradle docker
#- docker-compose -f ${root}/xml-wtf/docker-compose-gradle.yaml build --force-rm --no-cache --pull
#- docker-compose -f ${root}/xml-wtf/docker-compose-gradle.yaml up --force-recreate --remove-orphans &
#- sleep 20
#- http :8080
#- docker-compose -f ${root}/xml-wtf/docker-compose-gradle.yaml down -v

# monolith
- bash gradlew -b ${root}/monolith/build.gradle >/dev/null
- java -jar ${root}/monolith/app/build/libs/*.jar &
- bash mvnw -f ${root}/monolith/pom.xml >/dev/null
- java -jar ${root}/monolith/app/target/*.jar --server.port=8000 &
- wait_for 8080 8000
- http :8080
- http --stream :8080/api/v1/messages
- http :8000
- http --stream :8000/api/v1/messages 'accept:application/stream+json'
- stop_any 8080 8000

## listener-of-listener
#- bash gradlew -b ${root}/listener-of-listener/build.gradle >/dev/null
#- java -jar ${root}/listener-of-listener/kotlin-listeners/build/libs/*.jar &
#- bash mvnw -f ${root}/listener-of-listener/pom.xml >/dev/null
#- java -jar ${root}/listener-of-listener/kotlin-listeners/target/*.jar --server.port=8000 &
#- wait_for 8080 8000
#- http :8080
#- http :8080 message=send\ message,\ y0!
#- stop_any 8080 8000
## maven docker
#- docker-compose -f ${root}/listener-of-listener/docker-compose-maven.yaml build --force-rm --no-cache --pull
#- docker-compose -f ${root}/listener-of-listener/docker-compose-maven.yaml up --force-recreate --remove-orphans &
#- sleep 20
#- http :8080
#- http :8080 message=send\ message,\ y0!
#- docker-compose -f ${root}/listener-of-listener/docker-compose-maven.yaml down -v
## gradle docker
#- docker-compose -f ${root}/listener-of-listener/docker-compose-gradle.yaml build --force-rm --no-cache --pull
#- docker-compose -f ${root}/listener-of-listener/docker-compose-gradle.yaml up --force-recreate --remove-orphans &
#- sleep 20
#- http :8080
#- http :8080 message=send\ message,\ y0!
#- docker-compose -f ${root}/listener-of-listener/docker-compose-gradle.yaml down -v

# thymeleaf-webflux
- bash gradlew -b ${root}/thymeleaf-webflux/build.gradle >/dev/null
- java -jar ${root}/thymeleaf-webflux/reactive-thymeleaf/build/libs/*.jar &
- bash mvnw -f ${root}/thymeleaf-webflux/pom.xml >/dev/null
- java -jar ${root}/thymeleaf-webflux/reactive-thymeleaf/target/*.jar --server.port=8000 &
- wait_for 8080 8000
- http --stream :8080
- http --stream :8000
- stop_any 8080 8000
# maven docker
- bash gradlew -b ${root}/thymeleaf-webflux/build.gradle composeUp -Pprofile=maven
- http --stream :8080
- bash gradlew -b ${root}/thymeleaf-webflux/build.gradle composeDown -Pprofile=maven
# gradle docker
- bash gradlew -b ${root}/thymeleaf-webflux/build.gradle composeUp
- sleep 20
- http --stream :8080
- bash gradlew -b ${root}/thymeleaf-webflux/build.gradle composeDown

## rmi
#- bash gradlew -b ${root}/rmi/build.gradle >/dev/null
#- java -jar ${root}/rmi/spring-rmi-client/build/libs/*.jar &
#- bash mvnw -f ${root}/rmi/pom.xml >/dev/null
#- java -jar ${root}/rmi/spring-rmi-service/target/*.jar --server.port=8000 &
#- wait_for 8080 8000
#- http :8080/api/v1/users name=maksimko
#- http :8080/api/v1/users name=maks
#- http :8080/api/v1/users name=max
#- http :8080/api/v1/users
#- stop_any 8080 8000
## hotel maven docker
#- docker-compose -f ${root}/rmi/docker-compose.yaml build --force-rm --no-cache --pull
#- docker-compose -f ${root}/rmi/docker-compose.yaml up --force-recreate --remove-orphans &
#- sleep 20
#- http :8080/api/v1/users name=maksimko
#- http :8080/api/v1/users name=maks
#- http :8080/api/v1/users name=max
#- http :8080/api/v1/users
#- docker-compose -f ${root}/rmi/docker-compose.yaml down -v

## mailbox
#- bash gradlew clean build -b ${root}/mailbox/build.gradle >/dev/null
#- bash mvnw clean package -f ${root}/mailbox/pom.xml >/dev/null
#- java -jar ${root}/mailbox/webapp/target/*.jar &
#- wait_for 8080
#- http -a max:max get :8080/
#- stop_any 8080

## hotel gradle
#- bash gradlew clean build -b ${root}/hotel/build.gradle >/dev/null
#- java -jar ${root}/hotel/webapp/build/libs/*.jar &
#- docker-compose -f ${root}/hotel/reservations/docker-compose.yml up -d
#- java -jar ${root}/hotel/reservations/build/libs/*.jar &
#- wait_for 8080 8081
#- http :8081/api/v1/reservations
#- http :8080
#- http :8080?name=Gradle
#- http :8080/actuator/
#- http :8080/actuator/health
#- stop_any 8080 8081
## hotel maven docker
#- bash mvnw -f ${root}/hotel/pom.xml clean package -U >/dev/null
#- docker-compose -f ${root}/hotel/docker-compose.yaml build --force-rm --no-cache --pull
#- docker-compose -f ${root}/hotel/docker-compose.yaml up --force-recreate --remove-orphans &
#- sleep 20
#- http :8080
#- http :8080?name=Maven
#- http :8080/actuator/
#- http :8080/actuator/health
#- docker-compose -f ${root}/hotel/docker-compose.yaml down -v

## mustache-json gradle
#- bash gradlew build -b ${root}/mustache-json/build.gradle >/dev/null
#- java -jar ${root}/mustache-json/build/libs/*.jar &
#- sleep 10
#- http :8080
#- http :8080/hello/
#- http :8080/hello/mustache
#- stop_any 8080
#- bash ./gradlew clean build
## mustache-json docker
#- docker-compose -f ${root}/mustache-json/docker-compose.yaml build --force-rm --no-cache --pull
#- docker-compose -f ${root}/mustache-json/docker-compose.yaml up --force-recreate --remove-orphans &
#- sleep 20
#- http :8080
#- http :8080/hello
#- http :8080/hello/lol
#- docker-compose -f ${root}/mustache-json/docker-compose.yaml down -v

# reactive-ngrx gradle
- bash mvnw -f ${root}/reactive-ngrx/pom.xml
- java -jar ${root}/reactive-ngrx/target/*.jar &
- sleep 25
- http :8080
- stop_any 8080
- bash gradlew -b ${root}/reactive-ngrx/build.gradle
# reactive-ngrx docker
- docker-compose -f ${root}/reactive-ngrx/src/main/docker/docker-compose.yaml build --force-rm --no-cache --pull
- docker-compose -f ${root}/reactive-ngrx/src/main/docker/docker-compose.yaml up &
- sleep 30
- http :8001
- http :8002
- docker-compose -f ${root}/reactive-ngrx/src/main/docker/docker-compose.yaml down -v

#- >
#  for path in \
#    spring-shell \
#    reactive-websocket-sse \
#    spring-boot-under-the-hood \
#    reactive-auth \
#    reactive-security-client \
#    reactive-functional-security \
#    reactive-mongo-webflux-functional \
#    reactive-mongo-webflux \
#    reactive-webflux-spring-data-redis \
#    spring-integration-5-example \
#    functional-spring;
#  do
#    export project="${root}/$path"
#    cd ${project}
#    echo "build $path"
#    bash gradlew clean build >/dev/null 2>&1
#  done;
