group: edge
dist: trusty

language: java
jdk: oraclejdk8

install: true
before_install:

  # install docker-compose
  - sudo apt update
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # kill whatever punning on postgres / rabbitmq port
  - sudo kill $(sudo lsof -t -i:5432) | true
  - sudo kill $(sudo lsof -t -i:5672) | true
  - sudo kill $(sudo lsof -t -i:27017) | true

script:
  - export ROOT=$PWD
  - >
    for path in \
      09-spring-boot-under-the-hood \
      08-reactive-auth \
      07-reactive-security-client \
      06-reactive-functional-security \
      05-reactive-mongo-webflux-functional \
      04-reactive-mongo-webflux \
      03-reactive-webflux-spring-data-redis \
      02-spring-integration-5-example \
      01-functional-spring;
    do
      export TARGET="$ROOT/$path"
      cd $TARGET
      bash gradlew clean build
    done;

before_cache:
  - bash gradlew --stop
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
